<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PosbinduSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('posbindu')->insert([
            [
                'nama_posyandu' => 'Posyandu 1 Anggrek - Njetis',
                'dukuh' => 'Jetis',
                'nik' => rand(1000000000000000, 9999999999999999),
                'nama' => 'Rudi',
                'umur_tahun' => 35,
                'tanggal_lahir' => '1989-03-15',
                'rt' => 1,
                'rw' => 2,
                'berat_badan' => 70.0,
                'tinggi_badan' => 175.0,
                'lemak_perut' => 15.0,
                'tensi_darah_sistolik' => 120.0,
                'tensi_darah_diastolik' => 80.0,
                'gula_darah' => 90.0,
                'kolesterol' => 180.0,
                'asam_urat' => 6.0,
                'lingkar_perut' => 85.0,
                'status_perokok' => 'Bukan Perokok',
                'riwayat_penyakit' => 'Tidak ada',
                'tanggal' => '2024-07-01',
            ],
            [
                'nama_posyandu' => 'Posyandu 2 Flamboyan - Sayangan',
                'dukuh' => 'Sayangan',
                'nik' => rand(1000000000000000, 9999999999999999),
                'nama' => 'Siti',
                'umur_tahun' => 42,
                'tanggal_lahir' => '1982-08-25',
                'rt' => 3,
                'rw' => 1,
                'berat_badan' => 65.0,
                'tinggi_badan' => 160.0,
                'lemak_perut' => 12.0,
                'tensi_darah_sistolik' => 130.0,
                'tensi_darah_diastolik' => 85.0,
                'gula_darah' => 95.0,
                'kolesterol' => 200.0,
                'asam_urat' => 7.0,
                'lingkar_perut' => 90.0,
                'status_perokok' => 'Perokok Pasif',
                'riwayat_penyakit' => 'Hipertensi',
                'tanggal' => '2024-07-02',
            ],
            [
                'nama_posyandu' => 'Posyandu 3 Riya - Wonorejo',
                'dukuh' => 'Wonorejo',
                'nik' => rand(1000000000000000, 9999999999999999),
                'nama' => 'Budi',
                'umur_tahun' => 50,
                'tanggal_lahir' => '1974-05-30',
                'rt' => 2,
                'rw' => 4,
                'berat_badan' => 80.0,
                'tinggi_badan' => 170.0,
                'lemak_perut' => 20.0,
                'tensi_darah_sistolik' => 135.0,
                'tensi_darah_diastolik' => 90.0,
                'gula_darah' => 110.0,
                'kolesterol' => 220.0,
                'asam_urat' => 8.0,
                'lingkar_perut' => 95.0,
                'status_perokok' => 'Perokok Aktif',
                'riwayat_penyakit' => 'Diabetes',
                'tanggal' => '2024-07-03',
            ],
            [
                'nama_posyandu' => 'Posyandu 4 Melati - Blimbing 4',
                'dukuh' => 'Blimbing',
                'nik' => rand(1000000000000000, 9999999999999999),
                'nama' => 'Dewi',
                'umur_tahun' => 29,
                'tanggal_lahir' => '1995-12-12',
                'rt' => 4,
                'rw' => 3,
                'berat_badan' => 58.0,
                'tinggi_badan' => 165.0,
                'lemak_perut' => 10.0,
                'tensi_darah_sistolik' => 110.0,
                'tensi_darah_diastolik' => 70.0,
                'gula_darah' => 85.0,
                'kolesterol' => 170.0,
                'asam_urat' => 5.5,
                'lingkar_perut' => 78.0,
                'status_perokok' => 'Bukan Perokok',
                'riwayat_penyakit' => 'Tidak ada',
                'tanggal' => '2024-07-04',
            ],
            [
                'nama_posyandu' => 'Posyandu 5 Dahlia - Blimbing 5',
                'dukuh' => 'Blimbing',
                'nik' => rand(1000000000000000, 9999999999999999),
                'nama' => 'Ani',
                'umur_tahun' => 37,
                'tanggal_lahir' => '1987-11-22',
                'rt' => 5,
                'rw' => 2,
                'berat_badan' => 75.0,
                'tinggi_badan' => 168.0,
                'lemak_perut' => 18.0,
                'tensi_darah_sistolik' => 125.0,
                'tensi_darah_diastolik' => 80.0,
                'gula_darah' => 100.0,
                'kolesterol' => 210.0,
                'asam_urat' => 6.5,
                'lingkar_perut' => 90.0,
                'status_perokok' => 'Bukan Perokok',
                'riwayat_penyakit' => 'Kadar kolesterol tinggi',
                'tanggal' => '2024-07-05',
            ],
        ]);
    }
}
